In [14]:
#https://www.youtube.com/watch?v=kft1AJ9WVDk
import numpy as np
def sigmoid(x):
    return 1/(1+np.exp(-x))

def sigmoid_derivatives(x):
    return x*(1-x)
    


trainning_inputs=np.array([[0,0,1],[1,1,1],[1,0,1],[0,1,1]])

training_outputs=np.array([[0,1,1,0]]).T

np.random.seed(1)

synaptic_weights=2*np.random.random((3,1))-1

print('random starting synaptic weights:')
print(synaptic_weights)

for iteration in range(100000):
    input_layer=trainning_inputs
    outputs=sigmoid(np.dot(input_layer,synaptic_weights))
    
    error=training_outputs-outputs  #calculated outputs-actual outputs
    adjusments=error*sigmoid_derivatives(outputs)
    synaptic_weights+=np.dot(input_layer.T,adjusments)
    
print('synaptic weights after training')
print(synaptic_weights)
print('Outputs after tranining: ')
print(outputs)


random starting synaptic weights:
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
synaptic weights after training
[[12.00870061]
 [-0.2044116 ]
 [-5.8002822 ]]
Outputs after tranining: 
[[0.00301758]
 [0.99753723]
 [0.99799161]
 [0.00246109]]
